/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MusicCatalogPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  baseFolder: "Music",
  notesSubfolder: "Notes",
  discogsToken: ""
};
function toYamlInline(items) {
  if (!items || items.length === 0)
    return "[]";
  const escaped = items.map((i) => `"${i.replace(/"/g, '\\"')}"`);
  return `[${escaped.join(", ")}]`;
}
var LOWERCASE_WORDS = /* @__PURE__ */ new Set([
  "a",
  "an",
  "the",
  "and",
  "but",
  "or",
  "nor",
  "for",
  "so",
  "yet",
  "at",
  "by",
  "in",
  "of",
  "on",
  "to",
  "up",
  "as",
  "is",
  "it"
]);
function toTitleCase(str) {
  if (!str)
    return str;
  const words = str.trim().split(/\s+/);
  return words.map((word, index) => {
    if (index === 0 || index === words.length - 1)
      return capitalizeWord(word);
    const clean = word.toLowerCase().replace(/[^a-z]/g, "");
    if (LOWERCASE_WORDS.has(clean))
      return word.toLowerCase();
    return capitalizeWord(word);
  }).join(" ");
}
function capitalizeWord(word) {
  if (!word)
    return word;
  if (word === word.toUpperCase() && /^[A-Z]/.test(word) && word.length <= 3)
    return word;
  if (word.includes("-"))
    return word.split("-").map((p) => capitalizeWord(p)).join("-");
  return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
}
function toTitleCaseNames(names) {
  return names.map((name) => name.split(/(\s+|,\s*)/).map((p) => capitalizeWord(p)).join(""));
}
var sleep = (ms) => new Promise((r) => setTimeout(r, ms));
function matchesFormatFilter(format, filter) {
  if (!filter)
    return true;
  const f = format.toLowerCase();
  if (filter === "cd")
    return f.includes("cd");
  if (filter === "lp")
    return f.includes("vinyl") || f === "lp" || f.includes('7"') || f.includes('10"') || f.includes('12"');
  return true;
}
function getNotesFolder(settings) {
  if (settings.notesSubfolder.trim())
    return `${settings.baseFolder}/${settings.notesSubfolder}`.replace(/\/+/g, "/");
  return settings.baseFolder;
}
function getBasePath(baseFolder) {
  return `${baseFolder}/Music Catalog.base`;
}
function generateBaseContent(settings) {
  const notesFolder = getNotesFolder(settings);
  return `filters:
  and:
    - file.hasTag("record")
    - file.inFolder("${notesFolder}")
properties:
  file.name:
    displayName: Album
views:
  - type: table
    name: All Releases
    order:
      - file.name
      - artists
      - label
      - releaseYear
      - format
      - genre
      - condition
      - copies
      - valuation
    sort:
      - property: file.name
        direction: ASC
  - type: table
    name: By Year
    order:
      - file.name
      - artists
      - label
      - releaseYear
      - format
      - condition
      - copies
    sort:
      - property: releaseYear
        direction: ASC
  - type: table
    name: By Artist
    order:
      - file.name
      - artists
      - label
      - releaseYear
      - format
      - copies
    sort:
      - property: artists
        direction: ASC
  - type: table
    name: Needs Condition
    filters:
      and:
        - condition == ""
    order:
      - file.name
      - artists
      - format
      - copies
      - upc
    sort:
      - property: file.name
        direction: ASC
`;
}
var MusicCatalogPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("disc", "Add Release by Barcode", () => new BarcodeModal(this.app, this).open());
    this.addCommand({ id: "add-release-by-barcode", name: "Add release by barcode", callback: () => new BarcodeModal(this.app, this).open() });
    this.addSettingTab(new MusicCatalogSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async ensureFolder(path) {
    if (!this.app.vault.getAbstractFileByPath(path))
      await this.app.vault.createFolder(path);
  }
  collectFiles(folder, results = []) {
    for (const child of folder.children) {
      if (child instanceof import_obsidian.TFile)
        results.push(child);
      else if (child instanceof import_obsidian.TFolder)
        this.collectFiles(child, results);
    }
    return results;
  }
  scanVaultForReleaseNotes() {
    return this.collectFiles(this.app.vault.getRoot()).filter((f) => {
      var _a, _b;
      if (f.extension !== "md")
        return false;
      const cache = this.app.metadataCache.getFileCache(f);
      return cache ? (_b = (_a = (0, import_obsidian.getAllTags)(cache)) == null ? void 0 : _a.includes("#record")) != null ? _b : false : false;
    });
  }
  findExistingBaseFile() {
    var _a;
    return (_a = this.collectFiles(this.app.vault.getRoot()).find((f) => f.extension === "base" && f.name === "Music Catalog.base")) != null ? _a : null;
  }
  async createBaseFile() {
    await this.ensureFolder(this.settings.baseFolder);
    const basePath = getBasePath(this.settings.baseFolder);
    const content = generateBaseContent(this.settings);
    const existing = this.app.vault.getAbstractFileByPath(basePath);
    if (existing instanceof import_obsidian.TFile) {
      await this.app.vault.modify(existing, content);
      new import_obsidian.Notice("\u2705 Music Catalog.base updated.");
    } else {
      await this.app.vault.create(basePath, content);
      new import_obsidian.Notice("\u2705 Music Catalog.base created.");
    }
  }
  async reorganizeFiles(releaseNotes) {
    const newNotesFolder = getNotesFolder(this.settings);
    const newBasePath = getBasePath(this.settings.baseFolder);
    await this.ensureFolder(this.settings.baseFolder);
    if (this.settings.notesSubfolder.trim())
      await this.ensureFolder(newNotesFolder);
    let moved = 0;
    for (const file of releaseNotes) {
      const newPath = `${newNotesFolder}/${file.name}`;
      if (file.path !== newPath) {
        await this.app.vault.rename(file, newPath);
        moved++;
      }
    }
    const existingBase = this.findExistingBaseFile();
    if (existingBase && existingBase.path !== newBasePath)
      await this.app.vault.rename(existingBase, newBasePath);
    await this.createBaseFile();
    await this.saveSettings();
    new import_obsidian.Notice(`\u2705 Reorganization complete. ${moved} note${moved !== 1 ? "s" : ""} moved.`);
  }
  // ─── UPC Barcode Lookup ───────────────────────────────────────────────────
  async lookupUPC(upc) {
    const cleanUPC = upc.replace(/[^0-9]/g, "");
    if (this.settings.discogsToken) {
      try {
        const r = await this.fetchDiscogs(cleanUPC);
        if (r)
          return r;
      } catch (e) {
        console.warn("Discogs lookup failed:", e);
      }
    }
    try {
      const r = await this.fetchMusicBrainz(cleanUPC);
      if (r)
        return r;
    } catch (e) {
      console.warn("MusicBrainz lookup failed:", e);
    }
    return null;
  }
  async fetchDiscogs(upc) {
    var _a;
    const url = `https://api.discogs.com/database/search?barcode=${upc}&type=release&token=${this.settings.discogsToken}`;
    const response = await (0, import_obsidian.requestUrl)({ url, headers: { "User-Agent": "ObsidianMusicCatalog/0.1" } });
    const data = response.json;
    if (!((_a = data.results) == null ? void 0 : _a.length))
      return null;
    return this.parseDiscogsResult(data.results[0], upc);
  }
  async fetchMusicBrainz(upc) {
    var _a;
    const url = `https://musicbrainz.org/ws/2/release?query=barcode:${upc}&fmt=json&inc=artist-credits+labels+genres+media`;
    const response = await (0, import_obsidian.requestUrl)({ url, headers: { "User-Agent": "ObsidianMusicCatalog/0.1 (obsidian-plugin)" } });
    const data = response.json;
    if (!((_a = data.releases) == null ? void 0 : _a.length))
      return null;
    return this.parseMBRelease(data.releases[0], upc);
  }
  // ─── Manual Title/Artist/Label Search ────────────────────────────────────
  // Result cap raised to 30 to handle common opera/classical titles that have
  // many recordings — e.g. "Aida" which has hundreds of pressings in Discogs.
  async searchReleases(params) {
    const { title, artist, label, composer, conductor, formatFilter } = params;
    const results = [];
    const seenKeys = /* @__PURE__ */ new Set();
    const dedupeKey = (r) => `${r.album.toLowerCase().trim()}|${(r.artists[0] || "").toLowerCase().trim()}|${r.releaseYear}`;
    const addResult = (r) => {
      const key = dedupeKey(r);
      if (!seenKeys.has(key)) {
        seenKeys.add(key);
        results.push(r);
      }
    };
    if (this.settings.discogsToken) {
      try {
        const dr = await this.searchDiscogs(title, artist, label, composer, conductor, formatFilter);
        dr.forEach(addResult);
      } catch (e) {
        console.warn("Discogs search failed:", e);
      }
    }
    try {
      const mbr = await this.searchMusicBrainz(title, artist, composer, conductor, formatFilter);
      mbr.forEach(addResult);
    } catch (e) {
      console.warn("MusicBrainz search failed:", e);
    }
    return results.slice(0, 30);
  }
  // ─── Discogs search ───────────────────────────────────────────────────────
  // per_page raised to 25 so obscure pressings of common titles are reachable.
  async searchDiscogs(title, artist, label, composer, conductor, formatFilter) {
    const artistTerms = [artist, composer, conductor].filter(Boolean);
    const seen = /* @__PURE__ */ new Set();
    const results = [];
    const discogsFormat = formatFilter === "cd" ? "CD" : formatFilter === "lp" ? "Vinyl" : "";
    const runQuery = async (artistTerm) => {
      let url = `https://api.discogs.com/database/search?release_title=${encodeURIComponent(title)}&type=release&per_page=25&token=${this.settings.discogsToken}`;
      if (artistTerm)
        url += `&artist=${encodeURIComponent(artistTerm)}`;
      if (label)
        url += `&label=${encodeURIComponent(label)}`;
      if (discogsFormat)
        url += `&format=${encodeURIComponent(discogsFormat)}`;
      const response = await (0, import_obsidian.requestUrl)({ url, headers: { "User-Agent": "ObsidianMusicCatalog/0.1" } });
      const data = response.json;
      for (const result of data.results || []) {
        const id = String(result.id);
        if (seen.has(id))
          continue;
        seen.add(id);
        results.push(this.parseDiscogsResult(result, ""));
      }
    };
    if (artistTerms.length > 0) {
      for (const term of artistTerms) {
        try {
          await runQuery(term);
        } catch (e) {
          console.warn(`Discogs search for "${term}" failed:`, e);
        }
      }
    } else {
      try {
        await runQuery("");
      } catch (e) {
        console.warn("Discogs title search failed:", e);
      }
    }
    return results;
  }
  // ─── MusicBrainz search ───────────────────────────────────────────────────
  // limit raised to 20 per query to surface deeper results before post-filtering.
  async searchMusicBrainz(title, artist, composer, conductor, formatFilter) {
    const escapedTitle = title.replace(/"/g, '\\"');
    const baseQuery = `release:"${escapedTitle}"`;
    const artistTerms = [artist, composer, conductor].filter(Boolean);
    const queries = artistTerms.length > 0 ? artistTerms.map((t) => `${baseQuery} AND artist:"${t.replace(/"/g, '\\"')}"`) : [baseQuery];
    const seen = /* @__PURE__ */ new Set();
    const results = [];
    for (let i = 0; i < queries.length; i++) {
      if (i > 0)
        await sleep(1100);
      try {
        const url = `https://musicbrainz.org/ws/2/release?query=${encodeURIComponent(queries[i])}&fmt=json&limit=20&inc=artist-credits+labels+genres+media`;
        const response = await (0, import_obsidian.requestUrl)({ url, headers: { "User-Agent": "ObsidianMusicCatalog/0.1 (obsidian-plugin)" } });
        const data = response.json;
        for (const r of data.releases || []) {
          if (seen.has(r.id))
            continue;
          const release = this.parseMBRelease(r, "");
          if (!matchesFormatFilter(release.format, formatFilter))
            continue;
          seen.add(r.id);
          results.push(release);
        }
      } catch (e) {
        console.warn(`MusicBrainz query "${queries[i]}" failed:`, e);
      }
    }
    return results;
  }
  // ─── Parsers ──────────────────────────────────────────────────────────────
  parseDiscogsResult(result, upc) {
    var _a;
    let album = result.title || "Unknown Album";
    let artistFromTitle = "";
    if (album.includes(" - ")) {
      const parts = album.split(" - ");
      artistFromTitle = parts[0].trim();
      album = parts.slice(1).join(" - ").trim();
    }
    const artists = result.artist ? [result.artist] : artistFromTitle ? [artistFromTitle] : [];
    return {
      upc,
      album: toTitleCase(album),
      artists: toTitleCaseNames(artists),
      label: Array.isArray(result.label) ? result.label[0] : result.label || "",
      catalogNumber: result.catno || "",
      releaseYear: ((_a = result.year) == null ? void 0 : _a.toString()) || "",
      genres: [...result.genre || [], ...result.style || []].slice(0, 5),
      format: Array.isArray(result.format) ? result.format[0] : result.format || "",
      coverUrl: result.cover_image || result.thumb || ""
    };
  }
  parseMBRelease(r, upc) {
    var _a, _b, _c, _d, _e, _f, _g;
    const artists = (r["artist-credit"] || []).filter((ac) => ac.artist).map((ac) => ac.artist.name);
    return {
      upc,
      album: toTitleCase(r.title || "Unknown Album"),
      artists: toTitleCaseNames(artists),
      label: ((_c = (_b = (_a = r["label-info"]) == null ? void 0 : _a[0]) == null ? void 0 : _b.label) == null ? void 0 : _c.name) || "",
      catalogNumber: ((_e = (_d = r["label-info"]) == null ? void 0 : _d[0]) == null ? void 0 : _e["catalog-number"]) || "",
      releaseYear: r.date ? r.date.substring(0, 4) : "",
      genres: (r.genres || []).slice(0, 5).map((g) => g.name),
      format: ((_g = (_f = r.media) == null ? void 0 : _f[0]) == null ? void 0 : _g.format) || "",
      coverUrl: ""
    };
  }
  // ─── Note Utilities ───────────────────────────────────────────────────────
  findExistingNote(release) {
    const folder = getNotesFolder(this.settings);
    const safeTitle = release.album.replace(/[\\/:*?"<>|]/g, "").trim();
    const file = this.app.vault.getAbstractFileByPath(`${folder}/${safeTitle}.md`);
    return file instanceof import_obsidian.TFile ? file : null;
  }
  async createReleaseNote(release, condition, acquired, valuation, copies) {
    const notesFolder = getNotesFolder(this.settings);
    await this.ensureFolder(this.settings.baseFolder);
    if (this.settings.notesSubfolder.trim())
      await this.ensureFolder(notesFolder);
    const safeTitle = release.album.replace(/[\\/:*?"<>|]/g, "").trim();
    await this.app.vault.create(`${notesFolder}/${safeTitle}.md`, this.generateNoteContent(release, condition, acquired, valuation, copies));
    new import_obsidian.Notice(`\u2705 Release added: ${release.album}`);
  }
  async updateCopies(file, newCount) {
    const content = await this.app.vault.read(file);
    const updated = /^copies:\s*\d+/m.test(content) ? content.replace(/^copies:\s*\d+/m, `copies: ${newCount}`) : content.replace(/^(---[\s\S]*?)\n---/m, `$1
copies: ${newCount}
---`);
    await this.app.vault.modify(file, updated);
    new import_obsidian.Notice(`\u2705 Copies updated to ${newCount}.`);
  }
  openNote(file) {
    this.app.workspace.getLeaf(false).openFile(file);
  }
  generateNoteContent(release, condition, acquired, valuation, copies) {
    const coverLine = release.coverUrl ? `
<img src="${release.coverUrl}" alt="cover" width="150"/>
` : "";
    const valuationYaml = valuation ? parseFloat(valuation) || `"${valuation}"` : '""';
    const copiesYaml = copies ? parseInt(copies) || 1 : 1;
    return `---
album: "${release.album.replace(/"/g, '\\"')}"
artists: ${toYamlInline(release.artists)}
label: "${release.label.replace(/"/g, '\\"')}"
catalogNumber: "${release.catalogNumber.replace(/"/g, '\\"')}"
releaseYear: ${release.releaseYear || '""'}
genre: ${toYamlInline(release.genres)}
format: "${release.format.replace(/"/g, '\\"')}"
upc: "${release.upc}"
cover: "${release.coverUrl}"
condition: "${condition}"
acquired: "${acquired}"
valuation: ${valuationYaml}
copies: ${copiesYaml}
tags: ["record"]
---
${coverLine}
## Notes

`;
  }
};
var BarcodeModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    this.showScanStep();
  }
  showScanStep() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Add Release" });
    const tabBar = contentEl.createDiv();
    tabBar.style.cssText = "display:flex; gap:0.5rem; margin-bottom:1.25rem;";
    const barcodeBtn = tabBar.createEl("button", { text: "\u{1F4F7}  Scan / UPC" });
    const searchBtn = tabBar.createEl("button", { text: "\u{1F50D}  Search by Title" });
    const activeStyle = "flex:1; padding:0.4rem; background:var(--interactive-accent); color:var(--text-on-accent); border-radius:4px; font-weight:500; cursor:pointer;";
    const inactiveStyle = "flex:1; padding:0.4rem; background:var(--background-secondary); border-radius:4px; cursor:pointer;";
    const tabContent = contentEl.createDiv();
    const renderBarcodeTab = () => {
      barcodeBtn.style.cssText = activeStyle;
      searchBtn.style.cssText = inactiveStyle;
      tabContent.empty();
      tabContent.createEl("p", { text: "Scan the UPC barcode with a USB scanner, or type it manually." }).style.cssText = "color:var(--text-muted); font-size:0.9rem; margin:0 0 0.75rem;";
      const inputEl = tabContent.createEl("input", { type: "text", placeholder: "UPC barcode..." });
      inputEl.style.cssText = "width:100%; margin-bottom:0.75rem; font-size:1.1rem; padding:0.5rem;";
      inputEl.focus();
      const statusEl = tabContent.createEl("p", { text: "" });
      statusEl.style.cssText = "color:var(--text-muted); min-height:1.5rem; margin:0 0 0.75rem;";
      const lookupBtn = tabContent.createEl("button", { text: "Look Up Release" });
      lookupBtn.style.cssText = "width:100%; padding:0.5rem;";
      const doLookup = async (upc) => {
        if (!upc) {
          statusEl.setText("Please enter a barcode.");
          return;
        }
        lookupBtn.disabled = true;
        inputEl.disabled = true;
        statusEl.setText("Looking up release...");
        const release = await this.plugin.lookupUPC(upc);
        if (!release) {
          statusEl.setText("\u274C No release found. Check the barcode and try again.");
          lookupBtn.disabled = false;
          inputEl.disabled = false;
          inputEl.focus();
          return;
        }
        const existing = this.plugin.findExistingNote(release);
        if (existing) {
          this.showDuplicateStep(release, existing);
          return;
        }
        this.showConfirmStep(release);
      };
      inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter")
          doLookup(inputEl.value.trim());
      });
      lookupBtn.addEventListener("click", () => doLookup(inputEl.value.trim()));
    };
    const renderSearchTab = () => {
      barcodeBtn.style.cssText = inactiveStyle;
      searchBtn.style.cssText = activeStyle;
      tabContent.empty();
      tabContent.createEl("p", { text: "Title is required. All other fields are optional." }).style.cssText = "color:var(--text-muted); font-size:0.9rem; margin:0 0 0.75rem;";
      const rowStyle = "display:flex; align-items:center; gap:0.75rem; margin-bottom:0.5rem;";
      const labelStyle = "min-width:80px; font-weight:500; font-size:0.9rem;";
      const inputStyle = "flex:1; padding:0.35rem;";
      const row = (parent, lbl, placeholder) => {
        const wrap = parent.createDiv();
        wrap.style.cssText = rowStyle;
        wrap.createEl("label", { text: lbl }).style.cssText = labelStyle;
        const el = wrap.createEl("input", { type: "text", placeholder });
        el.style.cssText = inputStyle;
        return el;
      };
      const titleEl = row(tabContent, "Title *", "Required");
      titleEl.focus();
      const artistEl = row(tabContent, "Artist", "Optional");
      const labelInputEl = row(tabContent, "Label", "Optional");
      let formatFilter = "";
      const filterWrap = tabContent.createDiv();
      filterWrap.style.cssText = "display:flex; align-items:center; gap:0.75rem; margin-bottom:0.75rem;";
      filterWrap.createEl("span", { text: "Format" }).style.cssText = "min-width:80px; font-weight:500; font-size:0.9rem;";
      const filterBtnGroup = filterWrap.createDiv();
      filterBtnGroup.style.cssText = "display:flex; gap:0.3rem;";
      const filterBtnActive = "padding:0.3rem 0.7rem; border-radius:4px; background:var(--interactive-accent); color:var(--text-on-accent); font-size:0.85rem; cursor:pointer;";
      const filterBtnInactive = "padding:0.3rem 0.7rem; border-radius:4px; background:var(--background-secondary); font-size:0.85rem; cursor:pointer;";
      const anyBtn = filterBtnGroup.createEl("button", { text: "Any" });
      const cdBtn = filterBtnGroup.createEl("button", { text: "CD Only" });
      const lpBtn = filterBtnGroup.createEl("button", { text: "LP Only" });
      const updateFilterBtns = () => {
        anyBtn.style.cssText = formatFilter === "" ? filterBtnActive : filterBtnInactive;
        cdBtn.style.cssText = formatFilter === "cd" ? filterBtnActive : filterBtnInactive;
        lpBtn.style.cssText = formatFilter === "lp" ? filterBtnActive : filterBtnInactive;
      };
      updateFilterBtns();
      anyBtn.addEventListener("click", () => {
        formatFilter = "";
        updateFilterBtns();
      });
      cdBtn.addEventListener("click", () => {
        formatFilter = "cd";
        updateFilterBtns();
      });
      lpBtn.addEventListener("click", () => {
        formatFilter = "lp";
        updateFilterBtns();
      });
      const classicalSep = tabContent.createDiv();
      classicalSep.style.cssText = "display:flex; align-items:center; gap:0.5rem; margin:0.25rem 0 0.5rem;";
      classicalSep.createEl("hr").style.cssText = "flex:1; border:none; border-top:1px solid var(--background-modifier-border);";
      classicalSep.createEl("span", { text: "Classical / Opera / Soundtrack" }).style.cssText = "font-size:0.78rem; color:var(--text-muted); white-space:nowrap;";
      classicalSep.createEl("hr").style.cssText = "flex:1; border:none; border-top:1px solid var(--background-modifier-border);";
      const composerEl = row(tabContent, "Composer", "Optional");
      const conductorEl = row(tabContent, "Conductor", "Optional");
      tabContent.createEl("p", { text: "Composer and conductor are each searched separately and results are merged." }).style.cssText = "color:var(--text-muted); font-size:0.78rem; margin:0.25rem 0 0.75rem;";
      const statusEl = tabContent.createEl("p", { text: "" });
      statusEl.style.cssText = "min-height:1.2rem; margin:0 0 0.5rem; font-size:0.85rem;";
      const searchActionBtn = tabContent.createEl("button", { text: "Search Releases" });
      searchActionBtn.style.cssText = "width:100%; padding:0.5rem; margin-bottom:0.75rem;";
      const resultsEl = tabContent.createDiv();
      const renderResults = (releases) => {
        resultsEl.empty();
        if (releases.length === 0) {
          resultsEl.createEl("p", { text: "No results found. Try different search terms." }).style.cssText = "color:var(--text-muted); font-size:0.9rem;";
          return;
        }
        resultsEl.createEl("p", { text: `${releases.length} result${releases.length !== 1 ? "s" : ""} \u2014 click to select` }).style.cssText = "font-size:0.8rem; color:var(--text-muted); margin-bottom:0.5rem;";
        releases.forEach((release) => {
          const card = resultsEl.createDiv();
          card.style.cssText = "display:flex; gap:0.65rem; padding:0.6rem; border-radius:6px; border:1px solid var(--background-modifier-border); margin-bottom:0.4rem; cursor:pointer; align-items:flex-start;";
          if (release.coverUrl) {
            const img = card.createEl("img");
            img.src = release.coverUrl;
            img.alt = "cover";
            img.style.cssText = "width:40px; height:auto; border-radius:3px; flex-shrink:0;";
          } else {
            const ph = card.createDiv();
            ph.style.cssText = "width:40px; height:40px; background:var(--background-secondary); border-radius:3px; flex-shrink:0; display:flex; align-items:center; justify-content:center; font-size:1.2rem;";
            ph.createEl("span", { text: "\u{1F4BF}" });
          }
          const info = card.createDiv();
          info.style.cssText = "flex:1; min-width:0;";
          info.createEl("div", { text: release.album }).style.cssText = "font-weight:600; font-size:0.9rem; white-space:nowrap; overflow:hidden; text-overflow:ellipsis;";
          if (release.artists.length > 0)
            info.createEl("div", { text: release.artists.join(", ") }).style.cssText = "color:var(--text-muted); font-size:0.82rem;";
          const meta = [release.label, release.releaseYear, release.format].filter(Boolean).join("  \xB7  ");
          if (meta)
            info.createEl("div", { text: meta }).style.cssText = "color:var(--text-muted); font-size:0.82rem;";
          if (release.genres.length > 0)
            info.createEl("div", { text: release.genres.join(", ") }).style.cssText = "color:var(--text-muted); font-size:0.78rem;";
          card.addEventListener("mouseenter", () => {
            card.style.background = "var(--background-secondary)";
          });
          card.addEventListener("mouseleave", () => {
            card.style.background = "";
          });
          card.addEventListener("click", () => {
            const existing = this.plugin.findExistingNote(release);
            if (existing) {
              this.showDuplicateStep(release, existing);
              return;
            }
            this.showConfirmStep(release);
          });
        });
      };
      const doSearch = async () => {
        const title = titleEl.value.trim();
        if (!title) {
          statusEl.setText("Please enter a title.");
          statusEl.style.color = "var(--color-red)";
          titleEl.focus();
          return;
        }
        statusEl.style.color = "var(--text-muted)";
        searchActionBtn.disabled = true;
        searchActionBtn.setText("Searching\u2026");
        const hasClassical = composerEl.value.trim() || conductorEl.value.trim();
        statusEl.setText(hasClassical ? "Running separate queries for composer/conductor \u2014 this may take a few seconds\u2026" : "Searching\u2026");
        resultsEl.empty();
        const releases = await this.plugin.searchReleases({
          title,
          artist: artistEl.value.trim(),
          label: labelInputEl.value.trim(),
          composer: composerEl.value.trim(),
          conductor: conductorEl.value.trim(),
          formatFilter
        });
        statusEl.setText("");
        searchActionBtn.disabled = false;
        searchActionBtn.setText("Search Releases");
        renderResults(releases);
      };
      const onEnter = (e) => {
        if (e.key === "Enter")
          doSearch();
      };
      [titleEl, artistEl, labelInputEl, composerEl, conductorEl].forEach((el) => el.addEventListener("keydown", onEnter));
      searchActionBtn.addEventListener("click", doSearch);
    };
    barcodeBtn.addEventListener("click", renderBarcodeTab);
    searchBtn.addEventListener("click", renderSearchTab);
    renderBarcodeTab();
  }
  showDuplicateStep(release, existing) {
    var _a, _b;
    const { contentEl } = this;
    contentEl.empty();
    const headerEl = contentEl.createDiv();
    headerEl.style.cssText = "display:flex; align-items:center; gap:0.5rem; margin-bottom:1rem;";
    headerEl.createEl("span", { text: "\u{1F4C0}" }).style.fontSize = "1.5rem";
    headerEl.createEl("h2", { text: "Already in your catalog" }).style.margin = "0";
    const previewEl = contentEl.createDiv();
    previewEl.style.cssText = "display:flex; gap:1rem; margin-bottom:1.25rem; align-items:flex-start;";
    if (release.coverUrl) {
      const imgEl = previewEl.createEl("img");
      imgEl.src = release.coverUrl;
      imgEl.alt = "cover";
      imgEl.style.cssText = "width:80px; height:auto; border-radius:4px; flex-shrink:0;";
    }
    const metaEl = previewEl.createDiv();
    metaEl.style.cssText = "display:flex; flex-direction:column; gap:0.2rem;";
    metaEl.createEl("strong", { text: release.album });
    if (release.artists.length > 0)
      metaEl.createEl("span", { text: release.artists.join(", ") }).style.cssText = "color:var(--text-muted); font-size:0.9rem;";
    if (release.label || release.releaseYear)
      metaEl.createEl("span", { text: [release.label, release.releaseYear].filter(Boolean).join(", ") }).style.cssText = "color:var(--text-muted); font-size:0.9rem;";
    if (release.format)
      metaEl.createEl("span", { text: release.format }).style.cssText = "color:var(--text-muted); font-size:0.9rem;";
    const cache = this.plugin.app.metadataCache.getFileCache(existing);
    const currentCopies = (_b = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.copies) != null ? _b : 1;
    const copiesInfoEl = contentEl.createDiv();
    copiesInfoEl.style.cssText = "background:var(--background-secondary); border-radius:6px; padding:0.65rem 0.9rem; margin-bottom:1.25rem; font-size:0.9rem;";
    copiesInfoEl.createEl("span", { text: "Currently in catalog: " });
    copiesInfoEl.createEl("strong", { text: `${currentCopies} cop${currentCopies === 1 ? "y" : "ies"}` });
    contentEl.createEl("hr").style.marginBottom = "1rem";
    const copiesWrap = contentEl.createDiv();
    copiesWrap.style.cssText = "display:flex; align-items:center; gap:0.75rem; margin-bottom:1.25rem;";
    copiesWrap.createEl("label", { text: "Update copies to" }).style.cssText = "min-width:120px; font-weight:500; font-size:0.9rem;";
    const copiesEl = copiesWrap.createEl("input", { type: "number" });
    copiesEl.value = String(currentCopies + 1);
    copiesEl.min = "1";
    copiesEl.step = "1";
    copiesEl.style.cssText = "flex:1; padding:0.35rem;";
    const btnCol = contentEl.createDiv();
    btnCol.style.cssText = "display:flex; flex-direction:column; gap:0.6rem;";
    const updateBtn = btnCol.createEl("button", { text: "\u2705  Update Copies" });
    updateBtn.style.cssText = "width:100%; padding:0.5rem; background:var(--interactive-accent); color:var(--text-on-accent); border-radius:4px;";
    const openBtn = btnCol.createEl("button", { text: "\u{1F4C0}  Open Existing Note" });
    openBtn.style.cssText = "width:100%; padding:0.5rem;";
    const scanBtn = btnCol.createEl("button", { text: "\u21A9  Search Again" });
    scanBtn.style.cssText = "width:100%; padding:0.5rem;";
    updateBtn.addEventListener("click", async () => {
      const newCount = parseInt(copiesEl.value) || currentCopies + 1;
      updateBtn.disabled = true;
      updateBtn.setText("Saving...");
      await this.plugin.updateCopies(existing, newCount);
      this.close();
    });
    openBtn.addEventListener("click", () => {
      this.plugin.openNote(existing);
      this.close();
    });
    scanBtn.addEventListener("click", () => this.showScanStep());
  }
  showConfirmStep(release) {
    const { contentEl } = this;
    contentEl.empty();
    const previewEl = contentEl.createDiv();
    previewEl.style.cssText = "display:flex; gap:1rem; margin-bottom:1.25rem; align-items:flex-start;";
    if (release.coverUrl) {
      const imgEl = previewEl.createEl("img");
      imgEl.src = release.coverUrl;
      imgEl.alt = "cover";
      imgEl.style.cssText = "width:80px; height:auto; border-radius:4px; flex-shrink:0;";
    }
    const metaEl = previewEl.createDiv();
    metaEl.style.cssText = "display:flex; flex-direction:column; gap:0.2rem;";
    metaEl.createEl("strong", { text: release.album });
    if (release.artists.length > 0)
      metaEl.createEl("span", { text: release.artists.join(", ") }).style.cssText = "color:var(--text-muted); font-size:0.9rem;";
    if (release.label || release.releaseYear)
      metaEl.createEl("span", { text: [release.label, release.releaseYear].filter(Boolean).join(", ") }).style.cssText = "color:var(--text-muted); font-size:0.9rem;";
    if (release.format)
      metaEl.createEl("span", { text: release.format }).style.cssText = "color:var(--text-muted); font-size:0.9rem;";
    if (release.genres.length > 0)
      metaEl.createEl("span", { text: release.genres.join(", ") }).style.cssText = "color:var(--text-muted); font-size:0.9rem;";
    contentEl.createEl("hr").style.marginBottom = "1rem";
    const rowStyle = "display:flex; align-items:center; gap:0.75rem; margin-bottom:0.75rem;";
    const labelStyle = "min-width:80px; font-weight:500;";
    const conditionWrap = contentEl.createDiv();
    conditionWrap.style.cssText = rowStyle;
    conditionWrap.createEl("label", { text: "Condition" }).style.cssText = labelStyle;
    const conditionEl = conditionWrap.createEl("select");
    conditionEl.style.cssText = "flex:1; padding:0.35rem;";
    ["", "Mint (M)", "Near Mint (NM)", "Very Good Plus (VG+)", "Very Good (VG)", "Good Plus (G+)", "Good (G)", "Fair (F)", "Poor (P)"].forEach((c) => {
      const opt = conditionEl.createEl("option", { text: c || "\u2014 select \u2014" });
      opt.value = c;
    });
    const acquiredWrap = contentEl.createDiv();
    acquiredWrap.style.cssText = rowStyle;
    acquiredWrap.createEl("label", { text: "Acquired" }).style.cssText = labelStyle;
    const acquiredEl = acquiredWrap.createEl("input", { type: "date" });
    acquiredEl.style.cssText = "flex:1; padding:0.35rem;";
    acquiredEl.value = new Date().toISOString().split("T")[0];
    const copiesWrap = contentEl.createDiv();
    copiesWrap.style.cssText = rowStyle;
    copiesWrap.createEl("label", { text: "Copies" }).style.cssText = labelStyle;
    const copiesEl = copiesWrap.createEl("input", { type: "number" });
    copiesEl.value = "1";
    copiesEl.min = "1";
    copiesEl.step = "1";
    copiesEl.style.cssText = "flex:1; padding:0.35rem;";
    const valuationWrap = contentEl.createDiv();
    valuationWrap.style.cssText = rowStyle + " margin-bottom:1.25rem;";
    valuationWrap.createEl("label", { text: "Value (USD)" }).style.cssText = labelStyle;
    const valuationPrefix = valuationWrap.createDiv();
    valuationPrefix.style.cssText = "display:flex; align-items:center; flex:1; border:1px solid var(--background-modifier-border); border-radius:4px; overflow:hidden;";
    valuationPrefix.createEl("span", { text: "$" }).style.cssText = "padding:0.35rem 0.5rem; background:var(--background-secondary); color:var(--text-muted); font-weight:500; border-right:1px solid var(--background-modifier-border);";
    const valuationEl = valuationPrefix.createEl("input", { type: "number" });
    valuationEl.placeholder = "0.00";
    valuationEl.min = "0";
    valuationEl.step = "0.01";
    valuationEl.style.cssText = "flex:1; padding:0.35rem 0.5rem; border:none; background:transparent; outline:none;";
    const btnRow = contentEl.createDiv();
    btnRow.style.cssText = "display:flex; gap:0.75rem; justify-content:flex-end;";
    const backBtn = btnRow.createEl("button", { text: "\u2190 Back" });
    const saveBtn = btnRow.createEl("button", { text: "Save Release" });
    saveBtn.style.cssText = "background:var(--interactive-accent); color:var(--text-on-accent); padding:0.4rem 1rem; border-radius:4px;";
    backBtn.addEventListener("click", () => this.showScanStep());
    saveBtn.addEventListener("click", async () => {
      saveBtn.disabled = true;
      saveBtn.setText("Saving...");
      await this.plugin.createReleaseNote(release, conditionEl.value, acquiredEl.value, valuationEl.value, copiesEl.value);
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ReorganizeModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    this.showScanStep();
  }
  showScanStep() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Reorganize Catalog Files" });
    contentEl.createEl("p", { text: "Scan your vault to find all release notes regardless of where they currently live." }).style.cssText = "color:var(--text-muted); font-size:0.9rem; margin-bottom:1.25rem;";
    const targetEl = contentEl.createDiv();
    targetEl.style.cssText = "background:var(--background-secondary); border-radius:6px; padding:0.75rem 1rem; margin-bottom:1.25rem; font-size:0.85rem;";
    targetEl.createEl("p", { text: "Target location (from your settings):" }).style.cssText = "font-weight:600; margin:0 0 0.4rem;";
    targetEl.createEl("p", { text: `\u{1F4C4} ${getBasePath(this.plugin.settings.baseFolder)}` }).style.cssText = "margin:0 0 0.2rem; color:var(--text-muted);";
    targetEl.createEl("p", { text: `\u{1F4C0} ${getNotesFolder(this.plugin.settings)}/` }).style.cssText = "margin:0; color:var(--text-muted);";
    const resultsEl = contentEl.createDiv();
    resultsEl.style.cssText = "min-height:2rem; margin-bottom:1rem;";
    const btnRow = contentEl.createDiv();
    btnRow.style.cssText = "display:flex; gap:0.75rem;";
    const cancelBtn = btnRow.createEl("button", { text: "Cancel" });
    cancelBtn.style.cssText = "flex:1; padding:0.5rem;";
    const scanBtn = btnRow.createEl("button", { text: "\u{1F50D}  Scan Vault" });
    scanBtn.style.cssText = "flex:1; padding:0.5rem; background:var(--interactive-accent); color:var(--text-on-accent); border-radius:4px;";
    cancelBtn.addEventListener("click", () => this.close());
    scanBtn.addEventListener("click", () => {
      var _a, _b;
      scanBtn.disabled = true;
      scanBtn.setText("Scanning...");
      resultsEl.empty();
      const releaseNotes = this.plugin.scanVaultForReleaseNotes();
      const newNotesFolder = getNotesFolder(this.plugin.settings);
      const notesToMove = releaseNotes.filter((f) => f.path !== `${newNotesFolder}/${f.name}`);
      const existingBase = this.plugin.findExistingBaseFile();
      const newBasePath = getBasePath(this.plugin.settings.baseFolder);
      const baseNeedsMove = !!(existingBase && existingBase.path !== newBasePath);
      const resultBox = resultsEl.createDiv();
      resultBox.style.cssText = "background:var(--background-secondary); border-radius:6px; padding:0.75rem 1rem; font-size:0.85rem;";
      resultBox.createEl("p", { text: `\u2705 Scan complete \u2014 found ${releaseNotes.length} release note${releaseNotes.length !== 1 ? "s" : ""} in your vault.` }).style.cssText = "font-weight:600; margin:0 0 0.5rem;";
      if (releaseNotes.length === 0) {
        resultBox.createEl("p", { text: 'No release notes found. Make sure notes have tags: ["record"] in their frontmatter.' }).style.cssText = "color:var(--text-muted); margin:0;";
        scanBtn.disabled = false;
        scanBtn.setText("\u{1F50D}  Scan Vault");
        return;
      }
      const byFolder = /* @__PURE__ */ new Map();
      for (const f of releaseNotes) {
        const folder = (_b = (_a = f.parent) == null ? void 0 : _a.path) != null ? _b : "(root)";
        if (!byFolder.has(folder))
          byFolder.set(folder, []);
        byFolder.get(folder).push(f);
      }
      byFolder.forEach((files, folder) => {
        const alreadyInPlace = folder === newNotesFolder;
        const folderEl = resultBox.createDiv();
        folderEl.style.cssText = "margin-bottom:0.3rem;";
        folderEl.createEl("span", { text: `\u{1F4C1} ${folder}/ \u2014 ${files.length} note${files.length !== 1 ? "s" : ""}` }).style.cssText = alreadyInPlace ? "color:var(--color-green); font-weight:500;" : "color:var(--text-muted);";
        if (alreadyInPlace)
          folderEl.createEl("span", { text: " \u2713 already in target" }).style.cssText = "color:var(--color-green); font-size:0.8rem;";
      });
      if (existingBase)
        resultBox.createEl("p", { text: `\u{1F4C4} Music Catalog.base: ${existingBase.path}` }).style.cssText = "margin:0.5rem 0 0; color:var(--text-muted);";
      if (notesToMove.length === 0 && !baseNeedsMove) {
        resultBox.createEl("p", { text: "\u2705 Everything is already in the correct location." }).style.cssText = "margin:0.75rem 0 0; font-weight:600; color:var(--color-green);";
        scanBtn.disabled = false;
        scanBtn.setText("\u{1F50D}  Scan Again");
        return;
      }
      const proceedRow = resultsEl.createDiv();
      proceedRow.style.cssText = "display:flex; justify-content:flex-end; margin-top:0.75rem;";
      const proceedBtn = proceedRow.createEl("button", { text: `Review ${notesToMove.length} move${notesToMove.length !== 1 ? "s" : ""} \u2192` });
      proceedBtn.style.cssText = "padding:0.4rem 1rem; background:var(--interactive-accent); color:var(--text-on-accent); border-radius:4px;";
      proceedBtn.addEventListener("click", () => this.showConfirmStep(releaseNotes, notesToMove, existingBase, baseNeedsMove));
      scanBtn.disabled = false;
      scanBtn.setText("\u{1F50D}  Scan Again");
    });
  }
  showConfirmStep(allNotes, notesToMove, existingBase, baseNeedsMove) {
    var _a, _b;
    const { contentEl } = this;
    contentEl.empty();
    const s = this.plugin.settings;
    const newNotesFolder = getNotesFolder(s);
    const newBasePath = getBasePath(s.baseFolder);
    contentEl.createEl("h2", { text: "Confirm Reorganization" });
    contentEl.createEl("p", { text: "Review the changes below before confirming." }).style.cssText = "color:var(--text-muted); font-size:0.9rem; margin-bottom:1rem;";
    const treeStyle = "background:var(--background-secondary); border-radius:6px; padding:0.75rem 1rem; font-family:monospace; font-size:0.82rem; margin-bottom:0.75rem; line-height:1.8;";
    if (notesToMove.length > 0) {
      contentEl.createEl("p", { text: "Release notes to move:" }).style.cssText = "font-weight:600; margin-bottom:0.25rem;";
      const notesBox = contentEl.createDiv();
      notesBox.style.cssText = treeStyle;
      const byFolder = /* @__PURE__ */ new Map();
      for (const f of notesToMove) {
        const folder = (_b = (_a = f.parent) == null ? void 0 : _a.path) != null ? _b : "(root)";
        if (!byFolder.has(folder))
          byFolder.set(folder, []);
        byFolder.get(folder).push(f);
      }
      byFolder.forEach((files, folder) => {
        notesBox.createEl("div", { text: `\u{1F4C1} ${folder}/` });
        const indent = notesBox.createDiv();
        indent.style.cssText = "padding-left:1.2rem;";
        files.slice(0, 4).forEach((f) => indent.createEl("div", { text: `\u{1F4C0} ${f.name}` }).style.cssText = "color:var(--text-muted);");
        if (files.length > 4)
          indent.createEl("div", { text: `\u2026 and ${files.length - 4} more` }).style.cssText = "color:var(--text-muted);";
        notesBox.createEl("div", { text: `\u21B3 \u2192 ${newNotesFolder}/` }).style.cssText = "padding-left:1.2rem; color:var(--color-green);";
      });
    }
    if (baseNeedsMove && existingBase) {
      contentEl.createEl("p", { text: "Base file to move:" }).style.cssText = "font-weight:600; margin-bottom:0.25rem;";
      const baseBox = contentEl.createDiv();
      baseBox.style.cssText = treeStyle;
      baseBox.createEl("div", { text: `\u{1F4C4} ${existingBase.path}` }).style.cssText = "color:var(--text-muted);";
      baseBox.createEl("div", { text: `\u21B3 \u2192 ${newBasePath}` }).style.cssText = "color:var(--color-green);";
    }
    const summaryEl = contentEl.createDiv();
    summaryEl.style.cssText = "background:var(--background-modifier-border); border-radius:6px; padding:0.6rem 0.9rem; margin-bottom:1.25rem; font-size:0.85rem;";
    summaryEl.createEl("p", { text: `\u{1F4C0} ${notesToMove.length} note${notesToMove.length !== 1 ? "s" : ""} \u2192 ${newNotesFolder}/` }).style.cssText = "margin:0 0 0.2rem;";
    if (baseNeedsMove)
      summaryEl.createEl("p", { text: `\u{1F4C4} Base \u2192 ${newBasePath}` }).style.cssText = "margin:0 0 0.2rem;";
    summaryEl.createEl("p", { text: "\u{1F4C4} Music Catalog.base will be regenerated with updated paths." }).style.cssText = "margin:0;";
    const btnRow = contentEl.createDiv();
    btnRow.style.cssText = "display:flex; gap:0.75rem; justify-content:flex-end;";
    const backBtn = btnRow.createEl("button", { text: "\u2190 Back" });
    backBtn.style.cssText = "padding:0.4rem 1rem;";
    const confirmBtn = btnRow.createEl("button", { text: "Confirm & Move Files" });
    confirmBtn.style.cssText = "background:var(--interactive-accent); color:var(--text-on-accent); padding:0.4rem 1rem; border-radius:4px;";
    backBtn.addEventListener("click", () => this.showScanStep());
    confirmBtn.addEventListener("click", async () => {
      confirmBtn.disabled = true;
      confirmBtn.setText("Moving files...");
      await this.plugin.reorganizeFiles(allNotes);
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var MusicCatalogSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Music Catalog Settings" });
    containerEl.createEl("h3", { text: "File Organization" });
    containerEl.createEl("p", { text: "Set where the catalog base file and release notes should live in your vault. After changing these paths, use the Reorganize Files section below to move existing files." }).style.cssText = "color:var(--text-muted); font-size:0.85rem; margin-bottom:0.75rem;";
    new import_obsidian.Setting(containerEl).setName("Catalog folder").setDesc("The top-level folder where Music Catalog.base will be created. Accepts nested paths, e.g. '03 Resources/Music'.").addText((text) => text.setPlaceholder("Music").setValue(this.plugin.settings.baseFolder).onChange(async (value) => {
      this.plugin.settings.baseFolder = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Notes subfolder").setDesc("A subfolder inside the catalog folder where individual release notes are stored. Default is 'Notes'. Leave blank to store notes directly in the catalog folder.").addText((text) => text.setPlaceholder("Notes").setValue(this.plugin.settings.notesSubfolder).onChange(async (value) => {
      this.plugin.settings.notesSubfolder = value.trim();
      await this.plugin.saveSettings();
    }));
    const previewEl = containerEl.createDiv();
    previewEl.style.cssText = "background:var(--background-secondary); border-radius:6px; padding:0.75rem 1rem; margin-bottom:1rem; font-size:0.85rem;";
    const updatePreview = () => {
      previewEl.empty();
      previewEl.createEl("p", { text: "Current target paths:" }).style.cssText = "font-weight:600; margin:0 0 0.4rem;";
      previewEl.createEl("p", { text: `\u{1F4C4} Base file: ${getBasePath(this.plugin.settings.baseFolder)}` }).style.cssText = "margin:0 0 0.25rem; color:var(--text-muted);";
      previewEl.createEl("p", { text: `\u{1F4C0} Release notes: ${getNotesFolder(this.plugin.settings)}/` }).style.cssText = "margin:0; color:var(--text-muted);";
    };
    updatePreview();
    const origSave = this.plugin.saveSettings.bind(this.plugin);
    this.plugin.saveSettings = async () => {
      await origSave();
      updatePreview();
    };
    new import_obsidian.Setting(containerEl).setName("Create or update base file").setDesc("Creates Music Catalog.base at the path shown above with the correct filters, views, and column layout.").addButton((btn) => btn.setButtonText("Create Base File").setCta().onClick(async () => {
      await this.plugin.createBaseFile();
    }));
    containerEl.createEl("hr").style.margin = "1.5rem 0";
    containerEl.createEl("h3", { text: "Reorganize Files" });
    containerEl.createEl("p", { text: "Use this after changing your folder settings to move existing release notes and the base file. Scans your entire vault first so manually-moved files are always found." }).style.cssText = "color:var(--text-muted); font-size:0.85rem; margin-bottom:0.75rem;";
    new import_obsidian.Setting(containerEl).setName("Scan & reorganize vault").setDesc("Opens a two-step dialog: scans for all release notes, shows what was found, then lets you confirm before moving anything.").addButton((btn) => btn.setButtonText("Scan Vault & Reorganize").setWarning().onClick(() => {
      new ReorganizeModal(this.app, this.plugin).open();
    }));
    containerEl.createEl("hr").style.margin = "1.5rem 0";
    containerEl.createEl("h3", { text: "API" });
    containerEl.createEl("p", { text: "MusicBrainz is always available with no setup required. Discogs provides richer data \u2014 pressing details, catalog numbers, and cover art \u2014 and is used as the primary source when a token is provided." }).style.cssText = "color:var(--text-muted); font-size:0.85rem; margin-bottom:0.75rem;";
    new import_obsidian.Setting(containerEl).setName("Discogs personal access token").setDesc("To generate one: log into Discogs \u2192 click your username \u2192 Settings \u2192 Developers \u2192 Generate new token. Do not use your Consumer Key or Consumer Secret \u2014 those are for OAuth and will not work.").addText((text) => text.setPlaceholder("Paste your Discogs personal access token here").setValue(this.plugin.settings.discogsToken).onChange(async (value) => {
      this.plugin.settings.discogsToken = value.trim();
      await this.plugin.saveSettings();
    }));
  }
};
